version: "3.9"

services:
  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_db:/data/db

  matching_service:
    container_name: matching_service
    build: ./MatchingService
    ports:
      - "3000:3000"
    depends_on:
      - redis

  user_service:
    container_name: user_service
    build: ./PeerPrep-UserService-main/user-service
    ports:
      - "3001:3001"
    depends_on:
      - mongo_db

  question_service:
    container_name: question_service
    build: ./QuestionService
    ports:
      - "3002:3002"
    depends_on:
      - mongo_db

  frontend:
    container_name: frontend_service
    build:
      context: ../frontend/peerprep # Path to the React app (peerprep)
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - PORT=5173
    depends_on:
      - user_service # Frontend waits for user_service to be up

volumes:
  mongo_db: {}
  redis_data: {}
