services:
  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_db:/data/db

  matching_service:
    container_name: matching_service
    build: ./MatchingService
    ports:
      - "8080:8080"
    depends_on:
      - redis
    develop:
      watch:
        - action: sync
          path: ./MatchingService
          target: ./app
        - path: ./MatchingService
          action: rebuild

  collaboration_service:
    container_name: collaboration_service
    build: ./CollaborationService
    ports:
      - "3004:3004"
    depends_on:
      - redis

  user_service:
    container_name: user_service
    build: ./PeerPrep-UserService-main/user-service
    ports:
      - "3001:3001"
    depends_on:
      - mongo_db
    develop:
      watch:
        - action: sync
          path: ./PeerPrep-UserService-main/user-service
          target: ./app
        - path: ./PeerPrep-UserService-main/user-service
          action: rebuild

  alfa_leetcode_api:
    container_name: alfa_leetcode_api
    image: alfaarghya/alfa-leetcode-api:2.0.1
    ports:
      - "3000:3000"
    restart: always

  question_service:
    container_name: question_service
    build: ./QuestionService
    ports:
      - "3002:3002"
    depends_on:
      - mongo_db
      - alfa_leetcode_api
    develop:
      watch:
        - action: sync
          path: ./QuestionService
          target: ./app
        - path: ./QuestionService
          action: rebuild

  frontend:
    container_name: frontend_service
    build:
      context: ../frontend/peerprep
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - PORT=5173
    depends_on:
      - user_service
    develop:
      watch:
        - action: sync
          path: ../frontend/peerprep
          target: ./app
        - path: ../frontend/peerprep/package.json
          action: rebuild

  chat_service:
    container_name: chat_service
    build: ./ChatService
    ports:
      - "8081:8081"
    environment:
      - CHAT_PORT=8081
      - FRONTEND_ORIGIN=http://localhost:5173
    depends_on:
      - frontend

volumes:
  mongo_db: {}
  redis_data: {}
