version: "3.9"

services:
  matching_service:
    container_name: matching_service
    build: ./
    ports:
      - "3000:3000"
    depends_on:
      - redis

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: {}
