apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: peerprep
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 3001
      # nodePort: 32658
  type: ClusterIP
